### ISSUE TITLE
Cannot run on Windows

### ISSUE THREAD

**Issue by teobugslayer** [tgardner/appbuilder-convert#3]
I got this error on Windows 10 x64:

```
>appbuilder-convert --source c:\sample-device\ --dest c:\ss2\
Starting AppBuilder conversion of 'sample-device'
Error: spawn cordova ENOENT
```

but I have Cordova CLI installed:

```
C:\Users\x>where cordova
C:\Users\x\AppData\Roaming\npm\cordova
C:\Users\x\AppData\Roaming\npm\cordova.cmd
```

I think the problem is that [here](https://github.com/tgardner/appbuilder-convert/blob/master/lib/converter.js#L60) you try executing a batch file as if it is a true executable.

I think you need to `spawn("cmd.exe", ["/c"] + the rest of original parameters)` instead.

**Comment by ryanskidmore** [comment]
I'm also having this issue

**Comment by schmookeeg** [comment]
Thanks for this, stumbled upon this issue and need. Here is a code snippet that works on windows. Replace line 60 in converter.js as referenced above, with the below:

```

            if(process.platform == "win32") { // windows
                parts.splice(0,0,"/C");
                var p = childProcess.spawn("cmd.exe", parts, opts);
            } else {  // unix, MacOS
                var p = childProcess.spawn(parts[0], parts.slice(1), opts);
            }

```
